name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug.
      placeholder: I can not start the game.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the bug.
      placeholder: "1. Go to..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Describe the expected behaviour after the steps above.
      placeholder: The game starts.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: Describe the actual behaviour after the steps above.
      placeholder: The game is crashing.
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Do you have any further information?
      placeholder: Further Information
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Which version of our software are you running?
      placeholder: e.g. X.X.X or X.X.X-xxxxx-XXXXXXXXXXXXXX
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which OS are you using?
      multiple: false
      options:
        - Ubuntu
        - NixOS
        - Other Linux Distribution
        - Windows
        - MacOS
      default: 0
  - type: dropdown
    id: download
    attributes:
      label: How did you download the software?
      options:
        - from GitHub release
        - apt
        - nix
        - built from source
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
